- name: "Create an ec2 instance and assign an elastic ip"
  hosts: localhost
  connection: local
  sudo_user: root
  gather_facts: False
  roles:
    - { role: common, tags: ec2 }

- name: "Bring up devstack"
  gather_facts: false
  hosts: all
  remote_user: ubuntu
  roles:
    # The below demonstrates how we can control the role behavior.
    # We could have done the below in one call "- role: devstack" would invoke setup and nova instance creation
    - { role: chrismeyersfsu.devstack, nova_setup: true, nova_groups: false, tags: devstack_setup }
    - { role: chrismeyersfsu.devstack, nova_setup: false, tags: devstack_nova }